### PR TITLE
Implements yarp clean

### LINKED ISSUE #7: Fixing yarpClean()
The function `yarpClean(...)` for now doesn't do anything, just a reminder for me.

### PR DESCRIPTION
**Pull request by Nicogene**
This PR implements yarp clean in the `NetworkProfiler`.
Before every profiling a message box ask to the user if he wants to run yarp clean before.

Fix #7.

Please review code

### CODE REVIEW

**Comment by apaikan** [comment]
good job @Nicogene!  Would be nice to have a edit box/scroll number in the message dialog before running the yarp clean to set/show the default `timeout` value!

**Review by apaikan — COMMENTED** [review]
I have not seen the code but as a reminder, please check that the timeout value entered by user is NOT zero ;)

(+1)

**Comment by Nicogene** [comment]
```
    if (timeout <= 0)
        timeout = -1;
```
In `NetworkProfiler` there is this check before performing yarp clean, is it ok?
However also inside `Companion::cmdClean()` there is the same check.

`timeout = -1` what does it mean?

**Comment by apaikan** [comment]
infinite! probably means no timeout

**Pull request merged**
